name: Build Mapsim Chat Binary

# اجرا وقتی یک release جدید منتشر می‌شود
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ چک کردن سورس از repo
      - uses: actions/checkout@v4

      # 2️⃣ نصب Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # 3️⃣ نصب dependencies و PyInstaller
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller

      # 4️⃣ ساخت باینری standalone
      - name: Build standalone binary
        run: |
          pyinstaller --onefile main.py --name mapsim_chat
          ls -lh dist/

      # 5️⃣ آپلود باینری به عنوان artifact
      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: mapsim_chat
          path: dist/mapsim_chat

      # 6️⃣ آپلود به release GitHub
      - name: Upload binary to GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: dist/mapsim_chat
          tag: ${{ github.event.release.tag_name }}
